### PR TITLE
chore(charts): disable localstack services

### PR DESCRIPTION
**Pull request by thbcmlowk**
## Description

Closes FL-1663

### Before

```bash
curl http://localhost:4566/_localstack/health
{"services": {"acm": "available", "apigateway": "available", "cloudformation": "available", "cloudwatch": "available", "config": "available", "dynamodb": "available", "dynamodbstreams": "available", "ec2": "available", "es": "available", "events": "available", "firehose": "available", "iam": "available", "kinesis": "available", "kms": "available", "lambda": "available", "logs": "available", "opensearch": "available", "redshift": "available", "resource-groups": "available", "resourcegroupstaggingapi": "available", "route53": "available", "route53resolver": "available", "s3": "available", "s3control": "available", "scheduler": "available", "secretsmanager": "available", "ses": "available", "sns": "available", "sqs": "available", "ssm": "available", "stepfunctions": "available", "sts": "available", "support": "available", "swf": "available", "transcribe": "available"}, "edition": "community", "version": "3.5.1.dev"}
```

### After

```bash
curl http://localhost:4566/_localstack/health
{"services": {"acm": "disabled", "apigateway": "disabled", "cloudformation": "disabled", "cloudwatch": "disabled", "config": "disabled", "dynamodb": "disabled", "dynamodbstreams": "disabled", "ec2": "disabled", "es": "disabled", "events": "disabled", "firehose": "disabled", "iam": "disabled", "kinesis": "disabled", "kms": "disabled", "lambda": "disabled", "logs": "disabled", "opensearch": "disabled", "redshift": "disabled", "resource-groups": "disabled", "resourcegroupstaggingapi": "disabled", "route53": "disabled", "route53resolver": "disabled", "s3": "available", "s3control": "disabled", "scheduler": "disabled", "secretsmanager": "disabled", "ses": "disabled", "sns": "disabled", "sqs": "disabled", "ssm": "disabled", "stepfunctions": "disabled", "sts": "disabled", "support": "disabled", "swf": "disabled", "transcribe": "disabled"}, "edition": "community", "version": "3.5.1.dev"}
```

## Checklist

- [ ] [changelog](../CHANGELOG.md) was updated with notable changes
- [ ] documentation was updated

### CODE REVIEW

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by thbcmlowk** [comment]
> Do we have a benchmark on memory use after deactivating unnecessary services?

We do not. 

This PR patches a configuration [behavior](https://github.com/Substra/substra-backend/blob/main/charts/substra-backend/values.yaml#L1104-L1105) that did not seem to work as expected. Assessing the impact of deactivating such services, in particular in regards of memory consumption is a follow-up task IMHO.

**Comment by thbcmlowk** [comment]
> > Do we have a benchmark on memory use after deactivating unnecessary services?
> 
> We do not.
> 
> This PR patches a [configuration](https://github.com/Substra/substra-backend/blob/main/charts/substra-backend/values.yaml#L1104-L1105) that did not seem to work as expected. Assessing the impact of deactivating such services, in particular in regards of memory consumption is a follow-up task IMHO.

Created [FL-1665](https://linear.app/owkin/issue/FL-1665/benchmark-localstack-after-service-removal)

**Review by SdgJlbl — APPROVED** [review]

**Pull request merged**
