### PR TITLE
refactor(helm): refactor initContainers in Helm helper templates

### PR DESCRIPTION
**Pull request by kaanyagci**
### Changed

- `add-ca-cert` `initContainer`  refactored as Helm helper template
- `wait-init-migrations` `initContainer` refactored to Helm helper template

## Checklist

- [ ] [changelog](../CHANGELOG.md) was updated with notable changes
- [ ] documentation was updated

### CODE REVIEW

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Review by oleobal — APPROVED** [review]

**Pull request merged**
