### PR TITLE
feat: stop cleaning up models using delete_intermediary_models

### PR DESCRIPTION
**Pull request by AlexandrePicosson**
## Description

Remove the code that was used to cleanup models in the compute engine.

## Motivation and Context

The `delete_intermediary_models` flag was removed from the API so it will always be `False` in the future, making this code useless.

## How Has This Been Tested?

e2e tests.
Result:
```
============ 110 passed, 7 skipped, 7 warnings in 558.47s (0:09:18) ============
```

### CODE REVIEW

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
Something happened while processing your message: Unexpected inputs provided: ["testsBenchmark"]

**Review by mblottiere — APPROVED** [review]

**Pull request merged**
