### PR TITLE
fix: load remote image once

### PR DESCRIPTION
**Pull request by guilhem-barthes**
## Description

Fixes FL-1440

## Checklist

- [ ] [changelog](../CHANGELOG.md) was updated with notable changes
- [ ] documentation was updated

### CODE REVIEW

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Review by SdgJlbl — APPROVED** [review]
I guess this do the job for now, but I'm wondering if the clean way of doing it would not be not to download the image if it already exists locally (whether the pod is going to be reused or not).
Definitely for a follow-up, though

**Pull request merged**
