### PR TITLE
chore: add limits and requests configuration in values (#867)

### PR DESCRIPTION
**Pull request by ThibaultFy**
## Description

closes FL-1547

### CODE REVIEW

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
e2e --tests mnist --refs substra-ci=chore/switch-requests-limits

**Comment by ThibaultFy** [comment]
/e2e --tests mnist --refs substra-ci=chore/switch-requests-limits

**Comment by ThibaultFy** [comment]
/e2e --tests mnist --refs substra-ci=chore/switch-requests-limits

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests mnist --refs substra-ci=chore/switch-requests-limits

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests mnist,doc,camelyon,substrafl --refs substra-ci=chore/switch-requests-limits

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests camelyon --refs substra-ci=chore/switch-requests-limits

**Comment by ThibaultFy** [comment]
/e2e --tests camelyon --refs substra-ci=chore/switch-requests-limits

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --tests camelyon, sdk, doc, mnist, substrafl, frontend

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Review by thbcmlowk — APPROVED** [review]
I like that!

**Comment by ThibaultFy** [comment]
@thbcmlowk have you carefully check what I did on the values file to add the prepopulate resources ? I added a section called `registryPrepopulate` with two container `waiteRegistry` and `pause`. I'm not sure about the naming nor the form...

**Pull request merged**
