### PR TITLE
fix: enforce use of `safezip` and `tarsafe`

### PR DESCRIPTION
**Pull request by guilhem-barthes**
## Description

Fixes FL-1470

It will also unlock this dependency update (which nicely flagged it: https://github.com/Substra/substra-backend/pull/813)

## Checklist

- [ ] [changelog](../CHANGELOG.md) was updated with notable changes
- [ ] documentation was updated

### CODE REVIEW

**Review by thbcmlowk — APPROVED** [review]
LGTM

**Comment by ThibaultFy** [comment]
Maybe launch the CI on this one no ?

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by guilhem-barthes** [comment]
> Maybe launch the CI on this one no ?

Really good call 🙏

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Pull request merged**
