### PR TITLE
chore: add missing repo

### PR DESCRIPTION
**Pull request by guilhem-barthes**
## Checklist

- [ ] [changelog](../CHANGELOG.md) was updated with notable changes
- [ ] documentation was updated

### CODE REVIEW

**Review by ThibaultFy — APPROVED** [review]
thanks 🙏

**Review by thbcmlowk — COMMENTED** [review]
What do you think about triggering the workflow at least on PR based on changes made on the `.github` workflow?
```diff
   pull_request:
     branches:
       - "main"
     paths:
       - "charts/**"
+      - ".github/workflows/helm.yml"
```

**Comment by guilhem-barthes** [comment]
> ```diff
> - ".github/workflows/helm.yml"
> ```

Sounds good ! But the problem are having is detected when we package, which only called during "publish". Should we add a package in each PR to try that no dependency is missed ?

**Comment by thbcmlowk** [comment]
> > ```diff
> > - ".github/workflows/helm.yml"
> > ```
> 
> Sounds good ! But the problem are having is detected when we package, which only called during "publish". Should we add a package in each PR to try that no dependency is missed ?

Yes, already did! https://github.com/Substra/substra-gha-workflows/pull/10

**Review by thbcmlowk — APPROVED** [review]
Re-triggered the CI after merge on GHA but LGTM! Thanks

**Pull request merged**
