### PR TITLE
feat: add output identifier in compute plan perf api

### PR DESCRIPTION
**Pull request by acellard**
## Description

Related to [asana task](https://app.asana.com/0/1200346939311555/1202721024997169)

Before Generic task, on frontend side performance series were build based on `metric key`. Now the equivalent unique key to identify a perf is `(task_key, algo_key, output_identifier)`. The output identifier should now be returned by compute plan perf endpoint.

This PR adds the output_identifier to metric field.
New api response : 
```javascript
        {
            "compute_task": {
                "key": "d4fea647-f799-436e-9181-3af75a861cec",
                "data_manager_key": "e7ccd2d4-b48d-4c3b-aa64-4cfbb42051d4",
                "algo_key": "8984a47c-7c34-4d54-8936-f9839c64acdb",
                "rank": 2,
                "round_idx": null,
                "data_samples": [
                    "f7beeee6-ce51-4f67-99cd-fa5237b73c86"
                ],
                "worker": "MyOrg1MSP"
            },
            "metric": {
                "key": "8984a47c-7c34-4d54-8936-f9839c64acdb",
                "name": "4a00d815120a4a7c90887d2978ee4117_global - Algo 0",
                "output_identifier": "performance"
            },
            "perf": 2.0
        }
    ],
    "compute_plan_statistics": {
        "compute_tasks_distinct_ranks": [
            1,
            2
        ],
        "compute_tasks_distinct_rounds": []
    }
```

## How has this been tested?
API was tested deploying isolated backend using data dump from previous local e2e run.

## Checklist

- [x] [changelog](../CHANGELOG.md) was updated with notable changes

### CODE REVIEW

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Review by cboillet-dev — APPROVED** [review]

**Pull request merged**
