### PR TITLE
feat: ensure building order

### PR DESCRIPTION
**Pull request by guilhem-barthes**
## Description

Add some tests on the order the functions are built. Part of FL-1147

## Checklist

- [x] [changelog](../CHANGELOG.md) was updated with notable changes
- [ ] documentation was updated

### CODE REVIEW

**Review by thbcmlowk — APPROVED** [review]
Thanks

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Pull request merged**
