### PR TITLE
fix: wait init migrations lack env var

### PR DESCRIPTION
**Pull request by guilhem-barthes**
## Description

Fixes FL-1589

## Checklist

- [ ] [changelog](../CHANGELOG.md) was updated with notable changes
- [ ] documentation was updated

### CODE REVIEW

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by guilhem-barthes** [comment]
CI running there: https://github.com/owkin/substra-ci/actions/runs/9447284050/job/26018770683

**Review by thbcmlowk — APPROVED** [review]
Thanks !

**Pull request merged**
