### PR TITLE
fix: metrics exporter redis not found

### PR DESCRIPTION
**Pull request by guilhem-barthes**
## Description

Add `redis` in metrics_exporter dependencies to fix `server.metrics`

## Checklist

- [ ] [changelog](../CHANGELOG.md) was updated with notable changes
- [ ] documentation was updated

### CODE REVIEW

**Review by SdgJlbl — APPROVED** [review]
Thanks 👍

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Pull request merged**
