### PR TITLE
feat: single generic task view

### PR DESCRIPTION
**Pull request by acellard**
## Description

This PR adds new endpoints returning all tasks regardless of category, dropping all category related fields.

Category related fields removed :
` category, aggregate, composite, predict, test, train`

Other fields removed :
`parent_tasks`

Two new routes have been added :
`/task` to list or retrieve existing tasks
`compute_plan/__key__/task` to list all task in a specific compute plan

## Checklist

- [ ] [changelog](../CHANGELOG.md) was updated with notable changes
- [ ] documentation was updated

### CODE REVIEW

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Review by AlexandrePicosson — APPROVED** [review]

**Review by Kelvin-M — APPROVED** [review]
LGTM, don't forget to update the [changelog](https://github.com/Substra/substra-backend/blob/main/CHANGELOG.md)

**Comment by sergebouchut2** [comment]
:arrow_up: rebase to solve conflict on changelog

**Pull request merged**
