### PR TITLE
fix: move more config to secrets

### PR DESCRIPTION
**Pull request by guilhem-barthes**
## Description

Move some secret values from configmaps to secrets

Fixes FL-1521

## Companion PR

- https://github.com/Substra/orchestrator/pull/408

## How has this been tested?

[CI](https://github.com/Substra/substra-backend/pull/889#issuecomment-2058149926)

## Checklist

- [x] [changelog](../CHANGELOG.md) was updated with notable changes
- [ ] documentation was updated

### CODE REVIEW

**Comment by Owlfred** [comment]
Error: Invalid ref

```
Usage: /e2e [options] [help]

/e2e may appear anywhere as long as it is on its own line

Options:
  --refs <value>                          Extra refs (branch or tag) with format REPO=GIT_REF,REPO=GIT_REF.
  Supported repositories: orchestrator, substra-backend, substra-frontend, substra-tools, substrafl, substra, substra-tests, substra-documentation, substra-ci.
  Example: /e2e --refs substra-backend=some_branch,orchestrator=some_tag (default: {})
  --tests-to-run, --tests <tests-to-run>  Comma-separated list of tests to run. Valid options: sdk, substrafl, doc, frontend, mnist, camelyon or NONE. Frontend tests will run automatically on substrafl, mnist and camelyon if selected. (default: "sdk")
  -h, --help                              display help for command
```

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Review by thbcmlowk — APPROVED** [review]
Assuming it has been tested with skaffold therefore no need to publish an alpha chart. Thanks for the work!

**Comment by guilhem-barthes** [comment]
> Assuming it has been tested with skaffold therefore no need to publish an alpha chart. Thanks for the work!

Yes I did test it locally with skaffold !

**Pull request merged**
