### PR TITLE
chore: secret key path

### PR DESCRIPTION
**Pull request by oleobal**
## Description

This is like #668, only without all the refactoring

To be rebased on main once #674 is merged

## How has this been tested?

⬇️ 

## Checklist

- [x] [changelog](../CHANGELOG.md) was updated with notable changes
- [x] documentation was updated

### CODE REVIEW

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by oleobal** [comment]
Closed in favour of #676

**Pull request closed without merging**
