### PR TITLE
feat: remove failed task category from compute plan API response

### PR DESCRIPTION
**Pull request by sergebouchut2**
Signed-off-by: Serge Bouchut <serge.bouchut@owkin.com>

## Description

Remove failed task category deprecated field from the compute plan API response in order to easily remove category field in the backend later.
See also:
- https://github.com/Substra/substra/pull/309
- https://github.com/Substra/substra-frontend/pull/134

## Checklist

- [x] [changelog](../CHANGELOG.md) was updated with notable changes
- [ ] documentation was updated

### CODE REVIEW

**Comment by sergebouchut2** [comment]
/e2e --refs substra=feat/remove_failed_task_category,substra-backend=feat/remove_failed_task_category --tests sdk,substrafl

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by ThibaultFy** [comment]
/e2e --refs substra=feat/remove_failed_task_category,substra-backend=feat/remove_failed_task_category --tests sdk,substrafl

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Review by ThibaultFy — COMMENTED** [review]
@guilhem-barthes shouldn't we also remove `failed_task_category` from the ComputePlan model ?

**Comment by Owlfred** [comment]
```
Usage: /e2e [options] [help]

/e2e may appear anywhere as long as it is on its own line

Options:
  --refs <value>                                         Extra refs (branch or tag) with format REPO=GIT_REF,REPO=GIT_REF.
  Supported repositories: substra-hlf-k8s, orchestrator, substra-backend, substra-frontend, substra-tools, substrafl, substra, substra-tests, substra-ci.
  Example: /e2e --refs substra-backend=some_branch,orchestrator=some_tag (default: {})
  --tests-to-run, --tests <tests-to-run>                 Comma-separated list of tests to run. Valid options: sdk,substrafl,frontend or NONE. (default: "sdk")
  --benchmarks-to-run, --benchmarks <benchmarks-to-run>  Comma-separated list of workflows tests to run. Valid options: mnist, camelyon or NONE. (default: "NONE")
  --orchestrator-mode, --mode <orchestrator-mode>        Comma-separated list of orchestrator modes to run tests for. Valid options: standalone,distributed (default: "standalone,distributed")
  -h, --help                                             display help for command
```

**Review by guilhem-barthes — APPROVED** [review]

**Pull request merged**
