### PR TITLE
chore: remove unused dependencies

### PR DESCRIPTION
**Pull request by SdgJlbl**

### CODE REVIEW

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Review by guilhem-barthes — CHANGES_REQUESTED** [review]
watchdog provides `watchmedo`, which is used when `settings:` is different than `prod`

**Comment by SdgJlbl** [comment]
> watchdog provides `watchmedo`, which is used when `settings:` is different than `prod`

for skaffold, right?
do we want to keep it in `requirements.txt` or should it be in `dev-requirements.txt`?

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by SdgJlbl** [comment]
> > watchdog provides `watchmedo`, which is used when `settings:` is different than `prod`
> 
> for skaffold, right? do we want to keep it in `requirements.txt` or should it be in `dev-requirements.txt`?

OK, it's actually used in the CI so I think it won't work if it's in the dev requirements. Reverted the change, thanks for the review 👍

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Review by guilhem-barthes — APPROVED** [review]

**Pull request merged**
