### PR TITLE
chore: rename compute task logs folder to asset logs folder

### PR DESCRIPTION
**Pull request by SdgJlbl**
## Description

Fixes FL-1421

## Checklist

- [ ] [changelog](../CHANGELOG.md) was updated with notable changes
- [ ] documentation was updated

### CODE REVIEW

**Review by guilhem-barthes — APPROVED** [review]
Thanks for this improvement!

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Pull request merged**
