### PR TITLE
feat: remove delete_intermediary_models field from the compute_plan view

### PR DESCRIPTION
**Pull request by AlexandrePicosson**
## Description

Remove the `delete_intermediary_models` field from the compute_plan view.

## Motivation and Context

This field should not be used anymore to control the cleanup of intermediary assets. Instead users should use the `transient` bool on task outputs.  It is already not sent by all the clients so we can safely remove it.

## How Has This Been Tested?

e2e tests.

### CODE REVIEW

**Comment by Owlfred** [comment]
```
Usage: /e2e [options] [help]

/e2e may appear anywhere as long as it is on its own line

Options:
  --refs <value>                                   Extra refs (branch or tag) with format REPO=GIT_REF,REPO=GIT_REF.
  Supported repositories: substra-hlf-k8s, orchestrator, substra-backend, substra-frontend, substra-tools, substrafl, substra, substra-tests, connect-ci.
  Example: /e2e --refs substra-backend=some_branch,orchestrator=some_tag (default: {})
  --tests-to-run, --tests <tests-to-run>           Comma-separated list of tests to run. Valid options: sdk,workflow,substrafl,frontend or NONE. (default: "sdk")
  --orchestrator-mode, --mode <orchestrator-mode>  Comma-separated list of orchestrator modes to run tests for. Valid options: standalone,distributed (default: "standalone,distributed")
  -h, --help                                       display help for command
```

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by AlexandrePicosson** [comment]
--mode=standalone --tests=sdk,frontend

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Review by sergebouchut2 — APPROVED** [review]

**Pull request merged**
