### PR TITLE
feat: check computeplans before running function

### PR DESCRIPTION
**Pull request by guilhem-barthes**
## Description

Fixes FL-1659

## Companion PR

- https://github.com/Substra/substra-tests/pull/383

## Checklist

- [ ] [changelog](../CHANGELOG.md) was updated with notable changes
- [ ] documentation was updated

### CODE REVIEW

**Comment by guilhem-barthes** [comment]
/e2e --tests sdk,substrafl,doc,mnist,frontend,camelyon --refs substra-tests=feat/check-computeplans-before-running-function

**Comment by guilhem-barthes** [comment]
/e2e --tests sdk --refs substra-tests=feat/check-computeplans-before-running-function

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by guilhem-barthes** [comment]
/e2e --tests sdk --refs substra-tests=feat/check-computeplans-before-running-function

**Review by SdgJlbl — APPROVED** [review]
LGTM

**Pull request merged**
