### PR TITLE
feat(charts): allow using existing secret for redis

### PR DESCRIPTION
**Pull request by thbcmlowk**
## Description

Part of FL-1642

## Checklist

- [ ] [changelog](../CHANGELOG.md) was updated with notable changes
- [ ] documentation was updated

### CODE REVIEW

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Review by SdgJlbl — APPROVED** [review]
Thanks, LGTM
do we want to test that this mechanism is working more permanently? By reusing a secret created independently on one of the dev instance, for example?

**Comment by thbcmlowk** [comment]
> Thanks, LGTM do we want to test that this mechanism is working more permanently? By reusing a secret created independently on one of the dev instance, for example?

Yes, this is planned! [Alpha chart version](https://github.com/Substra/substra-backend/actions/runs/9890898631) is already available in prevision. Stay tuned!

**Pull request merged**
