### PR TITLE
refactor!: remove model categories

### PR DESCRIPTION
**Pull request by mblottiere**
## Rationale

Model categories should not be used anymore

- frontend PR to remove model category: https://github.com/Substra/substra-frontend/pull/96
- sdk PR to remove model category: https://github.com/Substra/substra/pull/288

### CODE REVIEW

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Review by AlexandrePicosson — APPROVED** [review]

**Review by sergebouchut2 — APPROVED** [review]
let's go!

**Comment by mblottiere** [comment]
Thanks for the reviews

**Pull request merged**
