### PR TITLE
feat: remove `django-celery-results` and replace by redis

### PR DESCRIPTION
**Pull request by guilhem-barthes**
## Description

Fixes FL-1623

## Checklist

- [ ] [changelog](../CHANGELOG.md) was updated with notable changes
- [ ] documentation was updated

### CODE REVIEW

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Review by thbcmlowk — APPROVED** [review]
Thanks! 🧹

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Pull request merged**
