### PR TITLE
chore: remove unused ipython dependencies

### PR DESCRIPTION
**Pull request by oleobal**
## Description

Checking to see if #565 is needed

## How has this been tested?

CI below

## Checklist

- [ ] [changelog](../CHANGELOG.md) was updated with notable changes
- [ ] documentation was updated

### CODE REVIEW

**Comment by Owlfred** [comment]
End to end tests: :hourglass_flowing_sand: **STARTING**

**Review by ThibaultFy — APPROVED** [review]
thx !!

**Comment by oleobal** [comment]
@guilhem-barthes what do you think, do we merge this?

I'm unsure if the e2e tests cover everything ipython could be used for, maybe it's useful for dev stuff or whatnot.

**Review by mblottiere — APPROVED** [review]

**Comment by ThibaultFy** [comment]
Merge ?

**Comment by oleobal** [comment]
pros: make debugging on celery easier through a better shell
cons: we've never used it and it's two more dependencies

decision: remove it

**Pull request merged**
